import '@testing-library/jest-dom'

//  TESTING FILTERS
    //  FILTER IS INITIALISED AT DEFAULT VALUES
    //  ALL FILTERS ARE PRESENT (INCLUDING SLIDERS AND OTHER WIDGETS)
    //  CHANGE FILTER VALUES
    //  RESET FILTER AND EXPECT INITAL VALUES AGAIN

//  TESTING PROPERTY PAGE
    //  ADD THE PROPERTY TO FAVOURITE
    //  REMOVE THE PROPERTY FROM FAVOURITE

    //  CLICKING ON DIFFERENT TABS DISPLAY THEIR OWN CONTENT
    //  THUMBNAILS CHANGE CURRENT IMAGE

//  TESTING FAVOURITE PAGE
    //  (NONE YET COMPLETED)

    //  FAVOURITE PAGE DISPLAYS FAVOURITE PROPERTIES